In [60]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())  # 查看是否有GPU支持

2.8.0+cpu
False


In [61]:
x = torch.rand(5, 3)
print(x)



tensor([[0.6732, 0.6492, 0.8097],
        [0.7691, 0.8299, 0.8118],
        [0.2115, 0.1807, 0.5480],
        [0.7784, 0.2215, 0.0970],
        [0.0394, 0.1906, 0.2613]])


In [62]:
y = torch.zeros(5, 3)
print(y)
z = x + y
print(z)
print(x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6732, 0.6492, 0.8097],
        [0.7691, 0.8299, 0.8118],
        [0.2115, 0.1807, 0.5480],
        [0.7784, 0.2215, 0.0970],
        [0.0394, 0.1906, 0.2613]])
torch.Size([5, 3])


In [63]:
import numpy as np
a  = torch.ones(2, 2)
b = a.numpy()
print(b, type(b))

c = np.ones((2, 2))
d = torch.from_numpy(c) 
print(d, type(d))

[[1. 1.]
 [1. 1.]] <class 'numpy.ndarray'>
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) <class 'torch.Tensor'>


In [69]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()
print(out)
out.backward()
print(x.grad)  # 输出梯度

tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [65]:
learning_rate = 0.1
with torch.no_grad():  # 不记录梯度
    x -= learning_rate * x.grad  # 用梯度下降法更新x
print(x)
print(out)


tensor([[0.5500, 0.5500],
        [0.5500, 0.5500]], requires_grad=True)
tensor(27., grad_fn=<MeanBackward0>)


In [72]:
for i in range(5):
    y = x + 2
    z = y * y * 3
    out = z.mean()
    out.backward()
    with torch.no_grad():
        x -= learning_rate * x.grad
    x.grad.zero_()  # 清空梯度
    print(f"Step {i+1}, out = {round(out.item(),2)}")

Step 1, out = 0.0
Step 2, out = 0.0
Step 3, out = 0.0
Step 4, out = 0.0
Step 5, out = 0.0
